app:
  message: Application prod order-service update

server:
  port: 8081


resilience4j:
  circuitbreaker:
    instances:
      orderCB:
        failure-rate-threshold: 50
        minimum-number-of-calls: 5
        sliding-window-size: 10
        wait-duration-in-open-state: 10s

  retry:
    instances:
      orderCB:
        max-attempts: 3
        wait-duration: 2s



spring:
  sleuth:
    sampler:
      probability: 1.0   # trace all requests

  zipkin:
    base-url: http://localhost:9411
    sender:
      type: web
management:
  tracing:
    sampling:
      probability: 1.0
